sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: jr20051120041121
  alioss:
    bucketName: space-point
    region: cn-shanghai
    endPoint: https://oss-cn-shanghai.aliyuncs.com
