sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: jr20051120041121
  alioss:
    bucketName: space-point
    region: cn-shanghai
    endPoint: https://oss-cn-shanghai.aliyuncs.com
  redis:
    host: localhost
    password: 200511
    port: 6379
  wechat:
    appid: wx4f7daf48bfbe9f37
    secret: cc6ba39b1eae93c322b5f12adfbb560a